# Generated by Django 4.0.5 on 2022-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='epassword',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
