# Generated by Django 4.0.5 on 2022-06-04 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_employee_epassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('contactno', models.CharField(max_length=25, null=True)),
                ('portfolio_site', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='images/None/no-img.jpg', null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
