# Generated by Django 4.0.5 on 2022-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_userprofiledoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledoc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
