# Generated by Django 4.0.5 on 2022-06-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofileinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'permissions': [('save data', 'Can save data into database'), ('read data', 'Can only read data')]},
        ),
    ]
